# Generated by Django 2.2.5 on 2019-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.TextField()),
                ('book_name', models.TextField()),
                ('starting', models.DateField()),
                ('ending', models.DateField()),
            ],
        ),
    ]
