# Generated by Django 2.2 on 2019-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.TextField()),
                ('book_price', models.FloatField()),
                ('subject', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
