# Generated by Django 2.2 on 2019-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Id', models.IntegerField()),
                ('book_name', models.TextField()),
                ('bookprice', models.FloatField()),
                ('subject', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
