# Generated by Django 2.2 on 2019-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conest_name', models.TextField()),
                ('contest_type', models.TextField()),
                ('contest_site', models.TextField()),
                ('starting', models.DateField()),
                ('ending', models.DateField()),
            ],
        ),
    ]
